services:
  postgres:
    container_name: postgres-sql
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=render-spring
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - render-spring-network
    restart: always
  app:
    container_name: render-spring-app
    image: render-spring
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-sql:5432/render-spring
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
    networks:
      - render-spring-network

volumes:
  postgres:

networks:
  render-spring-network:
    driver: bridge
